import time 
print("O Combate Sagrado")
time.sleep(2)
print("seja bem vindo ao jogo, coloque seu nome e sua idade")
time.sleep(2)
(input("Insira seu nome!:"))
time.sleep(2)
idade = int(input("insira sua idade!:"))
time.sleep(2)
if idade >= 16:
    print("Idade aceita! ")
    time.sleep(2)
else:
    print("Idade recusada! ")
    time.sleep(2)
print("O jogo começa com a tela inicial")
print("aperte o play para começar")
print("O jogo começa")
print("Os jogadores ficam de frente")
print("Eles lutam")
print("nome dos jogadores, Kael e Nyx")
print("Saude dos personagens, eles tem cem de HP")
print("Nyx ataca Kael primeiro")
print("Nyx usa espada sombria")
print("ele usa tacando animais das trevas para atacar Kael")
print("Nyx tira vinte de HP de Kael")
print("Kael ira contratacar Nyx com seus poderes")
print("Kael usa ataque de fogo divino")
print("cria uma roda de fogo em torno de Nyx")
print("Kael tira vinte e três de HP de Nyx")
print("kael fica com oitenta de HP")
print("Nyx fica setenta e sete de HP")
print("o tempo acaba")
print("Kael vence a partida")